language: rust

os: 
  - linux

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cd "${TRAVIS_BUILD_DIR}/zeroable/"

        - cargo test --features nightly_testing
        - cargo test --features "nightly_testing print_type"

    - rust: 1.34.0

script:
  
  - cd "${TRAVIS_BUILD_DIR}/zeroable_derive/"
  - cargo test

  - cd "${TRAVIS_BUILD_DIR}/zeroable/"
  - cargo test --features testing
 
