language: rust

os: 
  - linux

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      script:
        - cd "${TRAVIS_BUILD_DIR}/zeroable/"

        - MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
        - echo "Installing latest nightly with Miri"
        - echo "$MIRI_NIGHTLY"
        - rustup set profile minimal
        - rustup default "$MIRI_NIGHTLY"
        - rustup override set "$MIRI_NIGHTLY"
        - rustup component add miri
        - cargo miri setup

        - cargo test --features nightly_testing
        - cargo test --features "nightly_testing print_type"

        - cargo clean

        - cargo miri test --features nightly_testing
        - cargo miri test --features "nightly_testing print_type"

    - rust: 1.34.0

script:
  
  - cd "${TRAVIS_BUILD_DIR}/zeroable_derive/"
  - cargo test

  - cd "${TRAVIS_BUILD_DIR}/zeroable/"
  - cargo test --features testing
 
